In [36]:
import pandas as pd

df = pd.read_csv("movie_dataset.csv")
df

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811
...,...,...,...,...,...,...,...,...,...
9995,10196,The Last Airbender,"Action,Adventure,Fantasy",en,"The story follows the adventures of Aang, a yo...",98.322,2010-06-30,4.7,3347
9996,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventure",en,The sharks take bite out of the East Coast whe...,12.490,2015-07-22,4.7,417
9997,13995,Captain America,"Action,Science Fiction,War",en,"During World War II, a brave, patriotic Americ...",18.333,1990-12-14,4.6,332
9998,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,Drama",en,A man named Farmer sets out to rescue his kidn...,15.159,2007-11-29,4.7,668
9999,455957,Domino,"Thriller,Action,Crime",en,Seeking justice for his partner’s murder by an...,16.482,2019-05-31,4.6,221

In [37]:
df.columns

Index(['id', 'title', 'genre', 'original_language', 'overview', 'popularity',
       'release_date', 'vote_average', 'vote_count'],
      dtype='object')

In [38]:
df.head()

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811

In [39]:
df.tail()

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
9995,10196,The Last Airbender,"Action,Adventure,Fantasy",en,"The story follows the adventures of Aang, a yo...",98.322,2010-06-30,4.7,3347
9996,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventure",en,The sharks take bite out of the East Coast whe...,12.490,2015-07-22,4.7,417
9997,13995,Captain America,"Action,Science Fiction,War",en,"During World War II, a brave, patriotic Americ...",18.333,1990-12-14,4.6,332
9998,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,Drama",en,A man named Farmer sets out to rescue his kidn...,15.159,2007-11-29,4.7,668
9999,455957,Domino,"Thriller,Action,Crime",en,Seeking justice for his partner’s murder by an...,16.482,2019-05-31,4.6,221

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 10000 non-null  int64
 1   title              10000 non-null  object
 2   genre              9997 non-null   object
 3   original_language  10000 non-null  object
 4   overview           9987 non-null   object
 5   popularity         10000 non-null  float64
 6   release_date       10000 non-null  object
 7   vote_average       10000 non-null  float64
 8   vote_count         10000 non-null  int64
dtypes: float64(2), int64(2), object(5)
memory usage: 703.2+ KB

In [41]:
df.isnull().sum()

id                    0
title                 0
genre                 3
original_language     0
overview             13
popularity            0
release_date          0
vote_average          0
vote_count            0
dtype: int64

In [42]:
df.shape

(10000, 9)

In [43]:
df

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811
...,...,...,...,...,...,...,...,...,...
9995,10196,The Last Airbender,"Action,Adventure,Fantasy",en,"The story follows the adventures of Aang, a yo...",98.322,2010-06-30,4.7,3347
9996,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventure",en,The sharks take bite out of the East Coast whe...,12.490,2015-07-22,4.7,417
9997,13995,Captain America,"Action,Science Fiction,War",en,"During World War II, a brave, patriotic Americ...",18.333,1990-12-14,4.6,332
9998,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,Drama",en,A man named Farmer sets out to rescue his kidn...,15.159,2007-11-29,4.7,668
9999,455957,Domino,"Thriller,Action,Crime",en,Seeking justice for his partner’s murder by an...,16.482,2019-05-31,4.6,221

In [44]:
df.title

0                            The Shawshank Redemption
1                         Dilwale Dulhania Le Jayenge
2                                       The Godfather
3                                    Schindler's List
4                              The Godfather: Part II
                            ...
9995                               The Last Airbender
9996                         Sharknado 3: Oh Hell No!
9997                                  Captain America
9998    In the Name of the King: A Dungeon Siege Tale
9999                                           Domino
Name: title, Length: 10000, dtype: object

In [45]:
df.columns

Index(['id', 'title', 'genre', 'original_language', 'overview', 'popularity',
       'release_date', 'vote_average', 'vote_count'],
      dtype='object')

In [46]:
df.overview

0       Framed in the 1940s for the double murder of h...
1       Raj is a rich, carefree, happy-go-lucky second...
2       Spanning the years 1945 to 1955, a chronicle o...
3       The true story of how businessman Oskar Schind...
4       In the continuing saga of the Corleone crime f...
                              ...
9995    The story follows the adventures of Aang, a yo...
9996    The sharks take bite out of the East Coast whe...
9997    During World War II, a brave, patriotic Americ...
9998    A man named Farmer sets out to rescue his kidn...
9999    Seeking justice for his partner’s murder by an...
Name: overview, Length: 10000, dtype: object

In [47]:
df.release_date

0       1994-09-23
1       1995-10-19
2       1972-03-14
3       1993-12-15
4       1974-12-20
           ...
9995    2010-06-30
9996    2015-07-22
9997    1990-12-14
9998    2007-11-29
9999    2019-05-31
Name: release_date, Length: 10000, dtype: object

In [48]:
df[['title','release_date']]

                                              title release_date
0                          The Shawshank Redemption   1994-09-23
1                       Dilwale Dulhania Le Jayenge   1995-10-19
2                                     The Godfather   1972-03-14
3                                  Schindler's List   1993-12-15
4                            The Godfather: Part II   1974-12-20
...                                             ...          ...
9995                             The Last Airbender   2010-06-30
9996                       Sharknado 3: Oh Hell No!   2015-07-22
9997                                Captain America   1990-12-14
9998  In the Name of the King: A Dungeon Siege Tale   2007-11-29
9999                                         Domino   2019-05-31

[10000 rows x 2 columns]

In [49]:
df.title.nunique()

9661

In [50]:
df.title.value_counts()

title
Beauty and the Beast                             4
Godzilla                                         3
Taxi                                             3
The Three Musketeers                             3
War of the Buttons                               3
                                                ..
Anplagghed al cinema                             1
Another Year                                     1
Fish Tank                                        1
The Tin Drum                                     1
In the Name of the King: A Dungeon Siege Tale    1
Name: count, Length: 9661, dtype: int64

In [51]:
df.isnull().sum()

id                    0
title                 0
genre                 3
original_language     0
overview             13
popularity            0
release_date          0
vote_average          0
vote_count            0
dtype: int64

In [52]:
# df.dropna(inplace=True)

In [53]:
df.shape

(10000, 9)

In [54]:
df.columns

Index(['id', 'title', 'genre', 'original_language', 'overview', 'popularity',
       'release_date', 'vote_average', 'vote_count'],
      dtype='object')

In [55]:
df = df[['id', 'title', 'genre', 'overview']]
df

,id,title,genre,overview
0,278,The Shawshank Redemption,"Drama,Crime",Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance","Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Drama,Crime","Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,"Drama,History,War",The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,"Drama,Crime",In the continuing saga of the Corleone crime f...
...,...,...,...,...
9995,10196,The Last Airbender,"Action,Adventure,Fantasy","The story follows the adventures of Aang, a yo..."
9996,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventure",The sharks take bite out of the East Coast whe...
9997,13995,Captain America,"Action,Science Fiction,War","During World War II, a brave, patriotic Americ..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,Drama",A man named Farmer sets out to rescue his kidn...
9999,455957,Domino,"Thriller,Action,Crime",Seeking justice for his partner’s murder by an...

In [56]:
df['movie_desc'] = df.overview + df.genre

C:\Users\visha\AppData\Local\Temp\ipykernel_13132\3054778402.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['movie_desc'] = df.overview + df.genre

In [57]:
df.head()

,id,title,genre,overview,movie_desc
0,278,The Shawshank Redemption,"Drama,Crime",Framed in the 1940s for the double murder of h...,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance","Raj is a rich, carefree, happy-go-lucky second...","Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Drama,Crime","Spanning the years 1945 to 1955, a chronicle o...","Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,"Drama,History,War",The true story of how businessman Oskar Schind...,The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,"Drama,Crime",In the continuing saga of the Corleone crime f...,In the continuing saga of the Corleone crime f...

In [58]:
df.drop(columns=['genre', 'overview'], inplace=True)

C:\Users\visha\AppData\Local\Temp\ipykernel_13132\3012924829.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['genre', 'overview'], inplace=True)

In [59]:
df.head()

,id,title,movie_desc
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=10000, stop_words='english')
cv

In [62]:
vector = cv.fit_transform(df.movie_desc.values.astype('U'))
vector = vector.toarray()

In [63]:
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [64]:
df.shape

(10000, 3)

In [65]:
df.title

0                            The Shawshank Redemption
1                         Dilwale Dulhania Le Jayenge
2                                       The Godfather
3                                    Schindler's List
4                              The Godfather: Part II
                            ...
9995                               The Last Airbender
9996                         Sharknado 3: Oh Hell No!
9997                                  Captain America
9998    In the Name of the King: A Dungeon Siege Tale
9999                                           Domino
Name: title, Length: 10000, dtype: object

In [66]:
from sklearn.metrics.pairwise import cosine_similarity
movie_similarity = cosine_similarity(vector)

In [67]:
movie_similarity

array([[1.        , 0.05634362, 0.12888482, ..., 0.07559289, 0.11065667,
        0.06388766],
       [0.05634362, 1.        , 0.07624929, ..., 0.        , 0.03636965,
        0.        ],
       [0.12888482, 0.07624929, 1.        , ..., 0.02273314, 0.06655583,
        0.08645856],
       ...,
       [0.07559289, 0.        , 0.02273314, ..., 1.        , 0.03253   ,
        0.02817181],
       [0.11065667, 0.03636965, 0.06655583, ..., 0.03253   , 1.        ,
        0.0412393 ],
       [0.06388766, 0.        , 0.08645856, ..., 0.02817181, 0.0412393 ,
        1.        ]])

In [68]:
movie_similarity.shape

(10000, 10000)

In [69]:
movie_similarity[0]

array([1.        , 0.05634362, 0.12888482, ..., 0.07559289, 0.11065667,
       0.06388766])

In [70]:
df.head(3)

,id,title,movie_desc
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."

In [76]:
def recommendation(movie):
    index = df[df.title == movie].index[0]
    dist = sorted(list(enumerate(movie_similarity[index])), reverse=True, key=lambda x: x[1])
    for i in dist[:10]:
        print(df.iloc[i[0]].title)

In [77]:
recommendation("Iron Man")

Iron Man
Iron Man 3
Guardians of the Galaxy Vol. 2
Avengers: Age of Ultron
Star Wars: Episode III - Revenge of the Sith
G.O.R.A.
Iron Man 2
Charlie's Angels
Everything Everywhere All at Once
Star Wars: Episode I - The Phantom Menace

In [78]:
recommendation("Star Wars")

Star Wars
The Empire Strikes Back
Star Wars: The Force Awakens
Return of the Jedi
Star Wars: Episode III - Revenge of the Sith
Star Trek VI: The Undiscovered Country
Star Wars: Episode I - The Phantom Menace
The Rocketeer
Iron Man
Star Wars: The Last Jedi

In [80]:
recommendation("Avengers: Age of Ultron")

Avengers: Age of Ultron
Iron Man
Iron Man 3
Deathstroke: Knights & Dragons - The Movie
Robot Overlords
Small Soldiers
Everything Everywhere All at Once
Stargate
The Humanity Bureau
The Transformers: The Movie

In [81]:
import pickle
pickle.dump(df, open("movie_list.pkl", "wb"))

In [82]:
pickle.dump(movie_similarity, open("movie_similarity.pkl", "wb"))